from dataclasses import dataclass
from typing import Protocol
from uuid import UUID

from sac.domain.cadastros import Customer, Product
from sac.domain.catalog import CatalogItem


class CatalogRepository(Protocol):
    async def list(self, search: str | None, active: bool | None) -> list[CatalogItem]: ...
    async def get(self, item_id: UUID) -> CatalogItem | None: ...
    async def get_by_name(self, name: str) -> CatalogItem | None: ...
    async def add(self, item: CatalogItem) -> None: ...
    async def update(self, item: CatalogItem) -> None: ...


class CustomerRepository(Protocol):
    async def list(
        self, search: str | None, active: bool | None, page: int, per_page: int
    ) -> tuple[list[Customer], int]: ...
    async def get(self, customer_id: UUID) -> Customer | None: ...
    async def get_by_document(self, document: str) -> Customer | None: ...
    async def add(self, customer: Customer) -> None: ...
    async def update(self, customer: Customer) -> None: ...


class ProductRepository(Protocol):
    async def list(
        self, search: str | None, active: bool | None, page: int, per_page: int
    ) -> tuple[list[Product], int]: ...
    async def get(self, product_id: UUID) -> Product | None: ...
    async def get_by_sku(self, sku: str) -> Product | None: ...
    async def add(self, product: Product) -> None: ...
    async def update(self, product: Product) -> None: ...


@dataclass(frozen=True)
class CepAddress:
    cep: str
    street: str
    neighborhood: str
    city: str
    state: str


class CepGatewayPort(Protocol):
    async def lookup(self, cep: str) -> CepAddress | None: ...
