from dataclasses import dataclass
from typing import Protocol
from uuid import UUID

from sac.domain.entities import Tenant, User, UserPreferences, UserTenant
from sac.domain.permissions import Role


@dataclass(frozen=True)
class TokenPayload:
    user_id: UUID
    tenant_slug: str | None
    role: Role | None
    is_super_admin: bool
    token_type: str


class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def list_all(self) -> list[User]: ...
    async def update(self, user: User) -> None: ...


class TenantRepository(Protocol):
    async def get_by_slug(self, slug: str) -> Tenant | None: ...
    async def get_by_id(self, tenant_id: UUID) -> Tenant | None: ...
    async def add(self, tenant: Tenant) -> None: ...
    async def list_all(self) -> list[Tenant]: ...
    async def update(self, tenant: Tenant) -> None: ...


class UserTenantRepository(Protocol):
    async def get(self, user_id: UUID, tenant_id: UUID) -> UserTenant | None: ...
    async def add(self, link: UserTenant) -> None: ...
    async def update(self, link: UserTenant) -> None: ...
    async def remove(self, user_id: UUID, tenant_id: UUID) -> None: ...
    async def list_for_tenant(self, tenant_id: UUID) -> list[UserTenant]: ...
    async def list_for_user(self, user_id: UUID) -> list[UserTenant]: ...


class UserPreferencesRepository(Protocol):
    async def get(self, user_id: UUID) -> UserPreferences | None: ...
    async def upsert(self, prefs: UserPreferences) -> None: ...


class PasswordHasherPort(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password_hash: str, password: str) -> bool: ...


class TokenServicePort(Protocol):
    def create_access(
        self, user_id: UUID, tenant_slug: str | None, role: Role | None, is_super_admin: bool
    ) -> str: ...
    def create_refresh(
        self, user_id: UUID, tenant_slug: str | None, role: Role | None, is_super_admin: bool
    ) -> str: ...
    def decode(self, token: str, expected_type: str) -> TokenPayload: ...


class TenantProvisionerPort(Protocol):
    async def provision(self, schema_name: str) -> None: ...
